version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: university_database
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  etl:
    build: .
    depends_on:
      - postgres
    environment:
      PG_USER: postgres
      PG_PASS: Morayoluwa@2020
      PG_HOST: postgres
      PG_PORT: 5432
      PG_NAME: university_database

volumes:
  pg_data:
